controllers_security:
    resource: ../src/Security/Controller/
    type: attribute

controllers_schedule:
    resource: ../src/Schedule/Controller/
    type: annotation

controllers_tweet:
    resource: ../src/Tweet/Controller/
    type: annotation

controllers_user:
    resource: ../src/User/Controller/
    type: annotation
